import { StyleSheet, Dimensions, Platform } from "react-native";

import { Brand } from '../../../constants/brand';
const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  chouchouBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: Brand.chouchou,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  chouchouBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.ink,
    letterSpacing: 0.8,
  },
  container: {
    flex: 1,
    backgroundColor: Brand.bg,
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 150,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 6,
  },
  brandTitle: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 3,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  brandTitleRed: {
    color: Brand.primaryDeep,
    fontWeight: '800',
  },
  brandTitleDark: {
    color: Brand.ink,
    fontWeight: '800',
  },
  hookContainer: {
    paddingHorizontal: 20,
    marginTop: 8,
    marginBottom: 16,
  },
  hookText: {
    fontSize: 28,
    fontWeight: '800',
    color: Brand.ink,
    letterSpacing: -0.8,
    lineHeight: 32,
  },
  hookSubtitle: {
    fontSize: 28,
    fontWeight: '800',
    color: Brand.primaryDeep,
    letterSpacing: -0.8,
    lineHeight: 32,
  },
  brutalistWrapper: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  brutalistContainer: {
    position: 'relative',
    height: 54,
  },
  shadowLayer: {
    display: 'none',
  },
  brutalistInputContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 54,
    borderRadius: 20,
    borderWidth: 0,
    backgroundColor: Brand.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    zIndex: 10,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
  brutalistSearchIcon: {
    marginRight: 10,
  },
  brutalistInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: Brand.ink,
    height: '100%',
    ...Platform.select({
      web: {
        outlineStyle: 'none',
        outlineWidth: 0,
        outlineColor: 'transparent',
        boxShadow: 'none',
        borderWidth: 0,
      } as any,
    }),
  },
  brutalistLabel: {
    position: 'absolute',
    top: -12,
    right: 20,
    borderRadius: 6,
    borderWidth: 0,
    backgroundColor: Brand.ink,
    paddingHorizontal: 10,
    paddingVertical: 3,
    zIndex: 20,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  brutalistLabelText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.white,
    letterSpacing: 1,
  },
  alertBanner: {
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: '#FFF3D6',
    borderWidth: 0,
    borderRadius: 18,
    padding: 14,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  alertBannerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  alertTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Brand.ink,
  },
  alertText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#92400E',
    lineHeight: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 12,
    gap: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: Brand.ink,
    letterSpacing: -0.4,
    flexShrink: 1,
  },
  seeAllText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.primaryDeep,
  },
  categoriesScroll: {
    paddingHorizontal: 20,
    gap: 12,
  },
  categoryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.white,
    borderWidth: 0,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 10,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  categoryCardActive: {
    backgroundColor: Brand.primaryDeep,
    borderWidth: 0,
  },
  categoryIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryName: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.ink,
  },
  categoryNameActive: {
    color: Brand.white,
  },
  categoryCountSub: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.inkSoft,
    marginTop: 1,
  },
  categoryCountSubActive: {
    color: 'rgba(255, 255, 255, 0.85)',
  },
  categorySkeleton: {
    width: 120,
    height: 48,
    borderRadius: 24,
    backgroundColor: Brand.line,
    marginRight: 12,
  },
  cardsScroll: {
    paddingHorizontal: 20,
    gap: 16,
  },
  largeCard: {
    width: 280,
    backgroundColor: Brand.white,
    borderRadius: 20,
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
    marginBottom: 6,
  },
  largeCardImage: {
    width: '100%',
    height: 170,
  },
  largeCardSkeleton: {
    width: 280,
    height: 260,
    borderRadius: 20,
    backgroundColor: Brand.line,
    marginRight: 16,
  },
  carouselPaginatorBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  carouselPaginatorBadgeSmall: {
    position: 'absolute',
    top: 10,
    left: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 12,
  },
  paginatorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  paginatorDotSmall: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  paginatorDotActive: {
    backgroundColor: Brand.white,
    width: 14,
  },
  ratingBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.white,
    borderRadius: 14,
    borderWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.ink,
  },
  ratingTextSmall: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.ink,
  },
  largeCardInfo: {
    padding: 14,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  cardCategoryText: {
    fontSize: 12,
    fontWeight: '800',
    color: Brand.primaryDeep,
  },
  cardPriceText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.inkSoft,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: Brand.ink,
    marginBottom: 8,
  },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  locationText: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.inkSoft,
  },
  locationTextSmall: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.inkSoft,
  },
  favoriteButton: {
    minWidth: 44,
    height: 44,
    paddingHorizontal: 7,
    borderRadius: 20,
    backgroundColor: Brand.bg,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  favoriteButtonSmall: {
    minWidth: 44,
    height: 44,
    paddingHorizontal: 6,
    borderRadius: 20,
    backgroundColor: Brand.bg,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 3,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  likeCountText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.inkSoft,
  },
  likeCountTextSmall: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.inkSoft,
  },
  likeCountTextActive: {
    color: Brand.primaryDeep,
  },
  smallCard: {
    width: 200,
    backgroundColor: Brand.white,
    borderRadius: 20,
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
    marginBottom: 6,
  },
  smallCardImage: {
    width: '100%',
    height: 120,
  },
  smallCardSkeleton: {
    width: 200,
    height: 190,
    borderRadius: 20,
    backgroundColor: Brand.line,
    marginRight: 16,
  },
  smallCardInfo: {
    padding: 12,
  },
  smallCardCategory: {
    fontSize: 12,
    fontWeight: '800',
    color: Brand.primaryDeep,
    marginBottom: 2,
  },
  smallCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Brand.ink,
    marginBottom: 8,
  },
  eventsContainer: {
    paddingHorizontal: 20,
    gap: 16,
    marginBottom: 20,
  },
  eventCard: {
    flexDirection: 'row',
    borderRadius: 20,
    borderWidth: 0,
    backgroundColor: Brand.white,
    padding: 14,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
    marginBottom: 6,
  },
  eventDateBlock: {
    width: 52,
    height: 52,
    borderRadius: 20,
    borderWidth: 0,
    backgroundColor: Brand.bg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  eventDateDay: {
    fontSize: 18,
    fontWeight: '800',
    color: Brand.primaryDeep,
    lineHeight: 20,
  },
  eventDateMonth: {
    fontSize: 12,
    fontWeight: '800',
    color: Brand.ink,
    textTransform: 'uppercase',
  },
  eventDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: Brand.ink,
    marginBottom: 2,
  },
  eventMeta: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.inkSoft,
    marginBottom: 4,
  },
  eventDesc: {
    fontSize: 12,
    fontWeight: '500',
    color: '#4A4A58',
    lineHeight: 16,
    marginBottom: 6,
  },
  eventFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  eventPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: Brand.primaryDeep,
  },
  eventPlacesBadge: {
    backgroundColor: Brand.bg,
    borderWidth: 0,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  eventPlacesBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.inkSoft,
  },
  bookBtn: {
    backgroundColor: Brand.primaryDeep,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  bookBtnPressed: {
    opacity: 0.85,
  },
  bookBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.white,
  },
  emptyText: {
    fontSize: 14,
    color: Brand.inkSoft,
    fontWeight: '600',
    textAlign: 'center',
    marginVertical: 20,
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(43, 29, 70, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  confirmCard: {
    width: '90%',
    maxWidth: 340,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Brand.line,
    backgroundColor: Brand.white,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
    overflow: 'hidden',
  },
  confirmBody: {
    padding: 24,
    alignItems: 'center',
  },
  confirmKickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  confirmKicker: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: Brand.primaryDeep,
    textTransform: 'uppercase',
  },
  confirmTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: Brand.ink,
    textAlign: 'center',
    marginBottom: 6,
  },
  confirmDesc: {
    fontSize: 13,
    fontWeight: '500',
    color: Brand.inkSoft,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 18,
  },
  confirmMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  confirmPricePill: {
    backgroundColor: Brand.primarySoft,
    borderWidth: 1,
    borderColor: '#FCA5A5',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  confirmPriceText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.primaryDeep,
  },
  confirmPlacesPill: {
    backgroundColor: Brand.bg,
    borderWidth: 1,
    borderColor: Brand.line,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  confirmPlacesText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4A4A58',
  },
  confirmNoticeBox: {
    width: '100%',
    backgroundColor: Brand.bg,
    borderWidth: 1,
    borderColor: Brand.line,
    borderRadius: 12,
    padding: 10,
    marginBottom: 18,
  },
  confirmNoticeText: {
    fontSize: 12,
    color: Brand.inkSoft,
    lineHeight: 15,
    textAlign: 'center',
  },
  confirmActionsRow: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  confirmCancelBtn: {
    flex: 1,
    height: 42,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Brand.line,
    backgroundColor: Brand.bg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmCancelBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.inkSoft,
  },
  confirmSuccessBtn: {
    flex: 1.4,
    height: 42,
    borderRadius: 12,
    backgroundColor: Brand.primaryDeep,
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmSuccessBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.white,
  },
  btnPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  successCard: {
    width: '90%',
    maxWidth: 340,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Brand.line,
    backgroundColor: Brand.white,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
    overflow: 'hidden',
  },
  successBody: {
    padding: 24,
    alignItems: 'center',
  },
  successIconWrapper: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Brand.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  successKicker: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: Brand.primaryDeep,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  successTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: Brand.ink,
    textAlign: 'center',
    marginBottom: 4,
  },
  successEventTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Brand.inkSoft,
    textAlign: 'center',
    marginBottom: 8,
  },
  successDesc: {
    fontSize: 13,
    color: '#4A4A58',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 18,
  },
  successNoticeBox: {
    width: '100%',
    backgroundColor: Brand.bg,
    borderWidth: 1,
    borderColor: Brand.line,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    alignItems: 'center',
  },
  successNoticeTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.ink,
    marginBottom: 2,
  },
  successNoticeSubtitle: {
    fontSize: 12,
    color: Brand.inkSoft,
  },
  primaryCtaBtn: {
    width: '100%',
    height: 44,
    borderRadius: 12,
    backgroundColor: Brand.primaryDeep,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  primaryCtaBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.white,
  },
  secondaryCtaBtn: {
    width: '100%',
    height: 40,
    borderRadius: 12,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryCtaBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: Brand.inkSoft,
  },
  infoCard: {
    width: '90%',
    maxWidth: 340,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Brand.line,
    backgroundColor: Brand.white,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
    overflow: 'hidden',
  },
  infoBody: {
    padding: 24,
    alignItems: 'center',
  },
  infoIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoKicker: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: Brand.inkSoft,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: Brand.ink,
    textAlign: 'center',
    marginBottom: 8,
  },
  infoDesc: {
    fontSize: 13,
    color: Brand.inkSoft,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 18,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 1000,
  },
  overlayDismiss: {
    flex: 1,
  },
  drawerContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '85%',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 10,
  },
  drawerGlass: {
    flex: 1,
    backgroundColor: Brand.bg,
  },
  drawerDragZone: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: 10,
  },
  grabHandle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#E3DCE0',
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Brand.line,
  },
  drawerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: Brand.ink,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Brand.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  categoriesGrid: {
    padding: 20,
    paddingBottom: 160,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  gridItem: {
    width: '47%',
    backgroundColor: Brand.white,
    borderWidth: 0,
    borderRadius: 20,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  gridIconBg: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gridItemLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.ink,
    flex: 1,
  },
  gridItemCount: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.inkSoft,
    marginTop: 2,
  },
  gridItemCountSelected: {
    color: 'rgba(255, 255, 255, 0.85)',
  },
  filteredViewContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 44,
  },
  /* ── 1. SIBLING CATEGORY CAROUSEL ── */
  editorialCategoryScrollWrap: {
    marginBottom: 12,
    marginHorizontal: -16,
  },
  editorialCategoryScroll: {
    paddingHorizontal: 16,
    gap: 8,
  },
  editorialCatPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.white,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 7,
    borderWidth: 1,
    borderColor: '#F5F0F2',
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  editorialCatPillActive: {
    backgroundColor: Brand.primaryDeep,
    borderColor: Brand.primary,
    shadowColor: Brand.ink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 6,
    elevation: 2,
  },
  editorialCatPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4A4A58',
  },
  editorialCatPillTextActive: {
    color: Brand.white,
    fontWeight: '800',
  },

  /* ── 2. EDITORIAL CATEGORY HERO CARD ── */
  editorialHeroCard: {
    backgroundColor: Brand.white,
    borderRadius: 24,
    padding: 18,
    marginBottom: 16,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F5F0F2',
    gap: 14,
  },
  editorialHeroHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  editorialHeroLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  editorialIconBox: {
    width: 48,
    height: 48,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editorialTitleBlock: {
    flex: 1,
  },
  editorialLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  editorialEyebrow: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.primaryDeep,
    letterSpacing: 1,
  },
  editorialDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: '#E3DCE0',
  },
  editorialCountLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.inkSoft,
  },
  editorialTitleText: {
    fontSize: 22,
    fontWeight: '800',
    color: '#24242E',
    letterSpacing: -0.4,
  },
  editorialCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Brand.bg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Brand.line,
    marginLeft: 8,
  },
  editorialActionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  editorialFilterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#24242E',
    borderRadius: 20,
    paddingHorizontal: 16,
    height: 44,
    gap: 8,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  editorialFilterBtnActive: {
    backgroundColor: Brand.primaryDeep,
    shadowColor: Brand.ink,
  },
  editorialFilterBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.white,
    letterSpacing: 0.2,
  },
  editorialFilterBtnTextActive: {
    color: Brand.white,
  },
  editorialFilterBadge: {
    backgroundColor: Brand.white,
    borderRadius: 14,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  editorialFilterBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.primaryDeep,
  },
  editorialSearchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.bg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Brand.line,
    paddingHorizontal: 12,
    height: 44,
  },
  editorialSearchInput: {
    flex: 1,
    fontSize: 13,
    color: '#24242E',
    fontWeight: '600',
    paddingVertical: 0,
  },
  editorialSpecialitiesRow: {
    marginHorizontal: -18,
  },
  editorialSpecialitiesScroll: {
    paddingHorizontal: 18,
    gap: 8,
  },
  editorialSpecialityChip: {
    backgroundColor: Brand.bg,
    borderRadius: 28,
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: Brand.line,
  },
  editorialSpecialityChipActive: {
    backgroundColor: '#24242E',
    borderColor: '#24242E',
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 2,
  },
  editorialSpecialityChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4A4A58',
  },
  editorialSpecialityChipTextActive: {
    color: Brand.white,
    fontWeight: '800',
  },
  editorialSpecialityChipCount: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.inkSoft,
  },
  editorialSpecialityChipCountActive: {
    color: 'rgba(255, 255, 255, 0.75)',
  },
  editorialStatusBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F5F0F2',
  },
  editorialStatusLeft: {
    flex: 1,
  },
  editorialStatusText: {
    fontSize: 12,
    color: Brand.inkSoft,
    fontWeight: '600',
  },
  editorialResetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  editorialResetText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.primaryDeep,
  },
  editorialChangeSortBtn: {
    paddingVertical: 2,
  },
  editorialChangeSortText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.primaryDeep,
  },
  emptyFilteredBox: {
    backgroundColor: Brand.white,
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#F5F0F2',
    marginTop: 8,
  },
  emptyFilteredTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: Brand.ink,
    marginBottom: 6,
  },
  emptyFilteredSub: {
    fontSize: 13,
    color: Brand.inkSoft,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 18,
  },
  emptyResetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.ink,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  emptyResetBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.white,
  },
  cardHeaderMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  cardPricePill: {
    backgroundColor: Brand.bg,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: Brand.line,
  },
  loadMoreBtn: {
    width: '100%',
    paddingVertical: 14,
    backgroundColor: Brand.ink,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  loadMoreBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.white,
  },
  activeFilterBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Brand.white,
    borderWidth: 0,
    borderRadius: 18,
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  activeFilterLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  activeFilterText: {
    fontSize: 13,
    color: Brand.inkSoft,
    fontWeight: '600',
  },
  clearFilterBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F5F0F2',
    borderWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  categoryCountBadge: {
    backgroundColor: Brand.primaryDeep,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  categoryCountBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.white,
  },
  gridItemSelected: {
    backgroundColor: Brand.primarySoft,
    borderColor: Brand.primary,
    borderWidth: 1.5,
  },
  gridItemLabelSelected: {
    color: Brand.primaryDeep,
    fontWeight: '800',
  },
  gridItemBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: Brand.white,
    borderWidth: 0,
    borderRadius: 14,
    paddingHorizontal: 6,
    paddingVertical: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  gridItemBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.ink,
  },
  filterTriggerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Brand.ink,
    borderRadius: 20,
    paddingHorizontal: 15,
    height: 40,
    gap: 7,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  filterTriggerButtonActive: {
    backgroundColor: Brand.primaryDeep,
    shadowColor: Brand.ink,
  },
  filterTriggerButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.white,
  },
  filterTriggerButtonTextActive: {
    color: Brand.white,
  },
  filterTriggerBadge: {
    backgroundColor: Brand.white,
    borderRadius: 8,
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  filterTriggerBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.primaryDeep,
  },

  /* Instant All Categories Modal */
  instantModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(43, 29, 70, 0.6)',
    justifyContent: 'flex-end',
  },
  instantModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  instantModalContent: {
    backgroundColor: Brand.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: height * 0.85,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 20,
  },
  instantModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F0F2',
    marginBottom: 16,
  },
  instantModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: Brand.ink,
  },
  instantModalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F5F0F2',
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* Precision Filter Modal */
  filterModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(43, 29, 70, 0.6)',
    justifyContent: 'flex-end',
  },
  filterModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  filterModalContent: {
    backgroundColor: Brand.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: height * 0.88,
    paddingTop: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 20,
  },
  filterModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F0F2',
  },
  filterModalIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: Brand.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#24242E',
  },
  filterModalSub: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.inkSoft,
  },
  filterModalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F5F0F2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterModalScroll: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },
  filterModalSection: {
    marginBottom: 20,
  },
  filterModalSectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#24242E',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  filterModalChipsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterModalChip: {
    backgroundColor: Brand.bg,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Brand.line,
  },
  filterModalChipActive: {
    backgroundColor: Brand.ink,
    borderColor: Brand.ink,
  },
  filterModalChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#3A3A48',
  },
  filterModalChipTextActive: {
    color: Brand.white,
    fontWeight: '800',
  },
  filterModalPriceRow: {
    flexDirection: 'row',
    gap: 8,
  },
  filterModalPriceCard: {
    flex: 1,
    backgroundColor: Brand.bg,
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Brand.line,
  },
  filterModalPriceCardActive: {
    backgroundColor: Brand.primarySoft,
    borderColor: Brand.primary,
    borderWidth: 1.5,
  },
  filterModalPriceLabel: {
    fontSize: 16,
    fontWeight: '800',
    color: '#3A3A48',
    marginBottom: 2,
  },
  filterModalPriceLabelActive: {
    color: Brand.primaryDeep,
  },
  filterModalPriceDesc: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.inkSoft,
  },
  filterModalPriceDescActive: {
    color: Brand.primaryDeep,
  },
  filterModalSortList: {
    gap: 8,
  },
  filterModalSortRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Brand.bg,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: Brand.line,
  },
  filterModalSortRowActive: {
    backgroundColor: Brand.primarySoft,
    borderColor: '#FCA5A5',
  },
  filterModalSortLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.ink,
    marginBottom: 2,
  },
  filterModalSortLabelActive: {
    color: Brand.primaryDeep,
  },
  filterModalSortDesc: {
    fontSize: 12,
    fontWeight: '500',
    color: Brand.inkSoft,
  },
  filterModalRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#E3DCE0',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  filterModalRadioActive: {
    borderColor: Brand.primary,
  },
  filterModalRadioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Brand.primaryDeep,
  },
  filterModalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: '#F5F0F2',
    backgroundColor: Brand.white,
    gap: 12,
  },
  filterModalResetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#F5F0F2',
  },
  filterModalResetText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.inkSoft,
  },
  filterModalApplyBtn: {
    flex: 1,
    backgroundColor: Brand.primaryDeep,
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Brand.ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 3,
  },
  filterModalApplyText: {
    fontSize: 14,
    fontWeight: '700',
    color: Brand.white,
  },
  verticalGridContainer: {
    gap: 14,
  },
  gridCardItem: {
    backgroundColor: Brand.white,
    borderRadius: 20,
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
    marginBottom: 4,
  },
  gridCardImage: {
    width: '100%',
    height: 160,
  },
  ratingBadgeGrid: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.white,
    borderWidth: 0,
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  gridCardBody: {
    padding: 14,
  },
  gridCardCategory: {
    fontSize: 12,
    fontWeight: '800',
    color: Brand.primaryDeep,
    marginBottom: 4,
  },
  gridCardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: Brand.ink,
    marginBottom: 8,
  },
  seeAllHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  seeAllTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: Brand.ink,
    flex: 1,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.white,
    borderWidth: 0,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  backBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.ink,
  },

  // ── NETFLIX TOP PARTENAIRES STYLES ──
  netflixSection: {
    marginBottom: 24,
  },
  netflixOfficialPill: {
    backgroundColor: Brand.primaryDeep,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 0,
  },
  netflixOfficialText: {
    color: Brand.white,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  netflixScroll: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    gap: 16,
  },
  netflixCardWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 260,
    marginRight: 10,
    position: 'relative',
  },
  netflixRankNumber: {
    fontSize: 64,
    fontWeight: '800',
    color: Brand.primary,
    lineHeight: 68,
    zIndex: 10,
    textShadowColor: Brand.white,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
    fontFamily: 'BricolageGrotesque_800ExtraBold',
    marginRight: -6,
  },
  netflixCardBody: {
    flex: 1,
    height: 150,
    backgroundColor: Brand.white,
    borderRadius: 20,
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: '#24242E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  netflixImage: {
    width: '100%',
    height: 85,
  },
  netflixBadgePill: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: Brand.chouchou,
    borderWidth: 0,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  netflixBadgeText: {
    color: Brand.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  netflixCardInfo: {
    padding: 8,
    backgroundColor: Brand.white,
    flex: 1,
    justifyContent: 'center',
  },
  netflixPartnerTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: Brand.ink,
  },
  netflixPartnerSubtitle: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.inkSoft,
    marginTop: 2,
  },
  homeFooterContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 36,
    paddingHorizontal: 20,
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.06)',
  },
  homeFooterBrand: {
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: Brand.primaryDeep,
    marginBottom: 4,
  },
  homeFooterDesc: {
    fontSize: 12,
    fontWeight: '500',
    color: Brand.inkSoft,
    marginBottom: 16,
    textAlign: 'center',
  },
  privacyPolicyFooterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(100, 116, 139, 0.08)',
    borderRadius: 28,
    marginBottom: 12,
  },
  privacyPolicyFooterText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4A4A58',
  },
  homeFooterCopyright: {
    fontSize: 12,
    color: Brand.inkSoft,
    textAlign: 'center',
  },
  progressionBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Brand.white,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    padding: 12,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Brand.line,
    ...Platform.select({
      ios: {
        shadowColor: '#24242E',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
      },
      android: {
        elevation: 2,
      },
      web: {
        boxShadow: '0 2px 10px rgba(43, 29, 70, 0.04)',
      } as any,
    }),
  },
  progressionContent: {
    flex: 1,
    marginRight: 10,
  },
  progressionTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  levelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  levelBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#24242E',
  },
  pointsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(232, 74, 95, 0.08)',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(232, 74, 95, 0.15)',
  },
  pointsBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.primaryDeep,
  },
  progressGaugeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressGaugeTrack: {
    flex: 1,
    height: 6,
    backgroundColor: '#F5F0F2',
    borderRadius: 3,
    overflow: 'hidden',
    marginRight: 8,
  },
  progressGaugeFill: {
    height: '100%',
    backgroundColor: '#1FA67A',
    borderRadius: 3,
  },
  progressGaugeLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.inkSoft,
  },
  privilegeShortcutBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: Brand.bg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(232, 74, 95, 0.2)',
  },
  privilegeShortcutText: {
    fontSize: 12,
    fontWeight: '700',
    color: Brand.primaryDeep,
    marginTop: 2,
  },
});



export default styles;
